listener 1883
# Peut etre a modifier
allow_anonymous true

protocol mqtt

listener 9001
protocol websockets

persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log

# Niveau de log
log_dest stdout
log_type all
