listener 1883
# Peut etre a modifier
allow_anonymous true # Permet les connexions anonymes (à désactiver en production pour plus de sécurité)

protocol mqtt # Utilise le protocole MQTT

listener 9001
protocol websockets # Active les WebSockets sur le port 9001 (ne nous a pas été utile)

persistence true # Active la persistance des messages
persistence_location /mosquitto/data/ # Emplacement des fichiers de persistance
log_dest file /mosquitto/log/mosquitto.log # Emplacement du fichier de log

# Niveau de log (très pratique pour dev, peut être enlevé en production)
log_dest stdout # Affiche les logs dans la sortie standard
log_type all # Enregistre tous les types de logs