services:

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/backend
    environment:
      FLASK_ENV: development
    networks:
      - app-network

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/frontend
    networks:
      - app-network

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    ports:
      - "1883:1883"  # Port MQTT standard
      - "9001:9001"  # WebSockets pour Vue.js
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/config/pwfile:/mosquitto/config/pwfile # JE sais pas a quoi ça sert
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    # security_opt:
    #   - no-new-privileges:true
    networks:
      - app-network
    
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    environment:
      POSTGRES_DB: sensorDb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: unless-stopped
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    networks:
      - app-network


volumes:
  db_data: # Volume pour une future base de données

networks:
  app-network:
    driver: bridge